@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Enum "<<Enumeration>> \nCommandWord" as CommandWord
Class CommandShortcut
Class CommandShortcutSet

CommandShortcut *-right-> "1" CommandWord
CommandShortcutSet o-right-> "*" CommandShortcut

@enduml
