@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FindClientCommandParser" as FindClientCommandParser LOGIC_COLOR
participant "a:FindClientCommand" as FindClientCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

box Storage STORAGE_COLOR_T1
participant ":Storage" as Storage STORAGE_COLOR
end box

[-> LogicManager : execute(find_client)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(find_client)
activate AddressBookParser

create FindClientCommandParser
AddressBookParser -> FindClientCommandParser
activate FindClientCommandParser

FindClientCommandParser --> AddressBookParser
deactivate FindClientCommandParser

AddressBookParser -> FindClientCommandParser
activate FindClientCommandParser
create FindClientCommand
FindClientCommandParser -> FindClientCommand
activate FindClientCommand

FindClientCommand --> FindClientCommandParser
deactivate FindClientCommand

FindClientCommandParser -> FindClientCommand : parse(find_client)
activate FindClientCommand

FindClientCommand -> FindClientCommandParser : a
deactivate FindClientCommand

FindClientCommandParser -> AddressBookParser : a
deactivate FindClientCommandParser

AddressBookParser -> LogicManager : a
deactivate AddressBookParser

LogicManager -> FindClientCommand : execute()
activate FindClientCommand

FindClientCommand -> Model : updateFilteredClientList(predicate)
activate Model

Model --> FindClientCommand
deactivate Model

FindClientCommand --> LogicManager : result
deactivate FindClientCommand
FindClientCommand -[hidden]-> LogicManager : result

LogicManager -> Storage : saveAddressBook(addressBook)
activate Storage

Storage --> LogicManager
deactivate Storage

[<--LogicManager

destroy FindClientCommand

deactivate LogicManager
@enduml
