@startuml


skinparam arrowThickness 1.1
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Abstract Class Id {
- id: int
{static} + MESSAGE_CONSTRAINTS: String
+ isValidId(): boolean
}

Package Client {
Class ClientId {
}
}

Package Hairdresser {
Class HairdresserId
}

Package Appointment {
Class AppointmentId
}

HairdresserId -up-|> Id
ClientId -up-|> Id
AppointmentId -up-|> Id

@enduml
