@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Abstract Class "{abstract} \nId" as Id {

}

Package Client {
Class ClientId {
}
}

Package Hairdresser {
Class HairdresserId
}

Package Appointment {
Class AppointmentId
}

HairdresserId -up-|> Id
ClientId -up-|> Id
AppointmentId -up-|> Id

@enduml
